### ISSUE TITLE
molden installer

### ISSUE THREAD

**Issue by leclercfl** [brewsci/homebrew-science#25] opened 2018-02-02 13:06 UTC
==> Installing molden from brewsci/science
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/molden.rb:18:in `<class:Molden>'
Please report this to the brewsci/science tap!

**Comment by sjackman** [comment] 2018-02-02 19:57
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

This issue is a duplicate of https://github.com/brewsci/homebrew-science/issues/14

**Closed by sjackman** 2018-02-02 19:57 UTC
Labels: duplicate
